/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AgentConversationMessageSchema extends BaseModel {
  static $columns = ['agent', 'attachments', 'content', 'conversationId', 'createdAt', 'id', 'meta', 'role', 'toolCalls', 'toolResults', 'updatedAt', 'usage', 'userId'] as const
  $columns = AgentConversationMessageSchema.$columns
  @column()
  declare agent: string
  @column()
  declare attachments: string
  @column()
  declare content: string
  @column()
  declare conversationId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare meta: string
  @column()
  declare role: string
  @column()
  declare toolCalls: string
  @column()
  declare toolResults: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare usage: string
  @column()
  declare userId: number | null
}

export class AgentConversationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'title', 'updatedAt', 'userId'] as const
  $columns = AgentConversationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class BetaRequestSchema extends BaseModel {
  static $columns = ['accountExpiresAt', 'approvedAt', 'approvedBy', 'createdAt', 'email', 'id', 'ipAddress', 'rejectionReason', 'status', 'token', 'tokenExpiresAt', 'updatedAt', 'userAgent', 'userId'] as const
  $columns = BetaRequestSchema.$columns
  @column.dateTime()
  declare accountExpiresAt: DateTime | null
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column()
  declare approvedBy: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipAddress: string | null
  @column()
  declare rejectionReason: string | null
  @column()
  declare status: string
  @column()
  declare token: string | null
  @column.dateTime()
  declare tokenExpiresAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: number | null
}

export class CacheSchema extends BaseModel {
  static $columns = ['expiration', 'key', 'value'] as const
  $columns = CacheSchema.$columns
  @column()
  declare expiration: number
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare value: string
}

export class CacheLockSchema extends BaseModel {
  static $columns = ['expiration', 'key', 'owner'] as const
  $columns = CacheLockSchema.$columns
  @column()
  declare expiration: number
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare owner: string
}

export class FailedJobSchema extends BaseModel {
  static $columns = ['connection', 'exception', 'failedAt', 'id', 'payload', 'queue', 'uuid'] as const
  $columns = FailedJobSchema.$columns
  @column()
  declare connection: string
  @column()
  declare exception: string
  @column.dateTime()
  declare failedAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare payload: string
  @column()
  declare queue: string
  @column()
  declare uuid: string
}

export class IngredientSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt', 'userId'] as const
  $columns = IngredientSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class JobBatchSchema extends BaseModel {
  static $columns = ['cancelledAt', 'createdAt', 'failedJobIds', 'failedJobs', 'finishedAt', 'id', 'name', 'options', 'pendingJobs', 'totalJobs'] as const
  $columns = JobBatchSchema.$columns
  @column()
  declare cancelledAt: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare failedJobIds: string
  @column()
  declare failedJobs: number
  @column()
  declare finishedAt: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare options: string | null
  @column()
  declare pendingJobs: number
  @column()
  declare totalJobs: number
}

export class JobSchema extends BaseModel {
  static $columns = ['attempts', 'availableAt', 'createdAt', 'id', 'payload', 'queue', 'reservedAt'] as const
  $columns = JobSchema.$columns
  @column()
  declare attempts: number
  @column()
  declare availableAt: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare payload: string
  @column()
  declare queue: string
  @column()
  declare reservedAt: number | null
}

export class MealTimeSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = MealTimeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MigrationSchema extends BaseModel {
  static $columns = ['batch', 'id', 'migration'] as const
  $columns = MigrationSchema.$columns
  @column()
  declare batch: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare migration: string
}

export class ModelHasPermissionSchema extends BaseModel {
  static $columns = ['modelId', 'modelType', 'permissionId', 'workspaceId'] as const
  $columns = ModelHasPermissionSchema.$columns
  @column()
  declare modelId: number
  @column()
  declare modelType: string
  @column()
  declare permissionId: number
  @column({ isPrimary: true })
  declare workspaceId: number
}

export class ModelHasRoleSchema extends BaseModel {
  static $columns = ['modelId', 'modelType', 'roleId', 'workspaceId'] as const
  $columns = ModelHasRoleSchema.$columns
  @column()
  declare modelId: number
  @column()
  declare modelType: string
  @column()
  declare roleId: number
  @column({ isPrimary: true })
  declare workspaceId: number
}

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'token'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare email: string
  @column()
  declare token: string
}

export class PermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'guardName', 'id', 'name', 'updatedAt'] as const
  $columns = PermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare guardName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PlannedMealSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'mealTimeId', 'plannedDate', 'recipeId', 'servingSize', 'updatedAt', 'userId', 'workspaceId'] as const
  $columns = PlannedMealSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mealTimeId: number
  @column.date()
  declare plannedDate: DateTime
  @column()
  declare recipeId: string
  @column()
  declare servingSize: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare workspaceId: number
}

export class RecipeIngredientSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'ingredientId', 'quantity', 'recipeId', 'unit', 'updatedAt'] as const
  $columns = RecipeIngredientSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ingredientId: string
  @column()
  declare quantity: string
  @column()
  declare recipeId: string
  @column()
  declare unit: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RecipeMealTimeSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'mealTimeId', 'recipeId', 'updatedAt'] as const
  $columns = RecipeMealTimeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mealTimeId: number
  @column()
  declare recipeId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RecipeTagSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'recipeId', 'tagId', 'updatedAt'] as const
  $columns = RecipeTagSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare recipeId: string
  @column()
  declare tagId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RecipeSchema extends BaseModel {
  static $columns = ['cookingTime', 'createdAt', 'description', 'id', 'imagePath', 'name', 'preparationTime', 'servingSize', 'updatedAt', 'userId'] as const
  $columns = RecipeSchema.$columns
  @column()
  declare cookingTime: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare imagePath: string | null
  @column()
  declare name: string
  @column()
  declare preparationTime: number
  @column()
  declare servingSize: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class RoleHasPermissionSchema extends BaseModel {
  static $columns = ['permissionId', 'roleId'] as const
  $columns = RoleHasPermissionSchema.$columns
  @column({ isPrimary: true })
  declare permissionId: number
  @column()
  declare roleId: number
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'guardName', 'id', 'name', 'updatedAt', 'workspaceId'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare guardName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare workspaceId: number | null
}

export class SessionSchema extends BaseModel {
  static $columns = ['id', 'ipAddress', 'lastActivity', 'payload', 'userAgent', 'userId'] as const
  $columns = SessionSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare lastActivity: number
  @column()
  declare payload: string
  @column()
  declare userAgent: string | null
  @column()
  declare userId: number | null
}

export class ShoppingListPlannedMealIngredientSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'ingredientId', 'isChecked', 'plannedMealId', 'shoppingListId', 'unit', 'updatedAt'] as const
  $columns = ShoppingListPlannedMealIngredientSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ingredientId: string
  @column()
  declare isChecked: boolean
  @column()
  declare plannedMealId: number
  @column()
  declare shoppingListId: number
  @column()
  declare unit: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ShoppingListSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'updatedAt', 'userId', 'weekStart', 'workspaceId'] as const
  $columns = ShoppingListSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column.date()
  declare weekStart: DateTime
  @column()
  declare workspaceId: number
}

export class StepSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'order', 'recipeId', 'updatedAt'] as const
  $columns = StepSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare order: number
  @column()
  declare recipeId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TagSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt', 'userId'] as const
  $columns = TagSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'emailVerifiedAt', 'id', 'locale', 'name', 'password', 'rememberToken', 'twoFactorConfirmedAt', 'twoFactorRecoveryCodes', 'twoFactorSecret', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locale: string
  @column()
  declare name: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare rememberToken: string | null
  @column.dateTime()
  declare twoFactorConfirmedAt: DateTime | null
  @column()
  declare twoFactorRecoveryCodes: string | null
  @column()
  declare twoFactorSecret: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WorkspaceInvitationSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'expiresAt', 'id', 'invitedBy', 'role', 'token', 'updatedAt', 'workspaceId'] as const
  $columns = WorkspaceInvitationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invitedBy: number
  @column()
  declare role: string
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare workspaceId: number
}

export class WorkspaceUserSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'joinedAt', 'updatedAt', 'userId', 'workspaceId'] as const
  $columns = WorkspaceUserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare joinedAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare workspaceId: number
}

export class WorkspaceSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isDefault', 'isPersonal', 'name', 'ownerId', 'updatedAt'] as const
  $columns = WorkspaceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isDefault: boolean
  @column()
  declare isPersonal: boolean
  @column()
  declare name: string
  @column()
  declare ownerId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
